"""Add sentiment and summary columns to news_articles

Revision ID: 2a2f400f2522
Revises: 
Create Date: 2025-04-16 15:16:22.483369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2f400f2522'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('news_articles', sa.Column('sentiment', sa.String(), nullable=True))
    op.add_column('news_articles', sa.Column('ai_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('news_articles', 'ai_summary')
    op.drop_column('news_articles', 'sentiment')
    # ### end Alembic commands ###
